### ISSUE TITLE
Error while adding crypto pairs in Simulation mode

### ISSUE THREAD

**Issue by galaxystakepool** [Drakkar-Software/OctoBot-Trading#504]
Hello,
when I try to add any pair I get this message:
![image](https://user-images.githubusercontent.com/80977541/114095433-151b7680-98c6-11eb-9251-c10a154e3e57.png)

for example:
COTI/USDT
ADA/USDT 

 2021-04-08 23:57:32,962 WARNING  PortfolioValueHolder[binance] No trading pair including COTI and USDT on binance. COTI can't be valued for portfolio and profitability.
 
 What pairs are supported in simulation mode?

Thanks!

**Comment by GuillaumeDSM** [comment]
Hi @galaxystakepool,
It should be any pair that is in the exchange(s) you are trading (in real or simulation) on.
