### ISSUE TITLE
Order created but not opened on exchange and octobot

### ISSUE THREAD

**Issue by valouvaliavlo** [Drakkar-Software/OctoBot-Trading#562]
[OctoBot.log](https://github.com/Drakkar-Software/OctoBot-Trading/files/6779474/OctoBot.log)
line 12939 the order is created but nothing after

Octobot version : 0.4.0b10

**Comment by valouvaliavlo** [comment]
Fixed by modifying log level to WARNING

**Comment by Herklos** [comment]
Which logging level ?

**Comment by valouvaliavlo** [comment]
> Which logging level ?
All. maybe some lag due to symbol wildcard
