### ISSUE TITLE
Difference between Kline and Candle (OHLCV)

### ISSUE THREAD

**Issue by vlastv** [Drakkar-Software/OctoBot-Trading#628]
I look in https://github.com/Drakkar-Software/OctoBot-Trading/tree/master/octobot_trading/exchange_data/kline and https://github.com/Drakkar-Software/OctoBot-Trading/tree/master/octobot_trading/exchange_data/ohlcv and do not understand the difference.

What is the difference between Kline and Candle (OHLCV)?

**Comment by Herklos** [comment]
Hi @vlastv, a Kline is the current candle, the one under construction. When its timeframe iteration is complete it becomes closed (added to the candles list) and a new one is created.
